### ISSUE TITLE
Cannot send message using mobile browser

### ISSUE THREAD

**Issue by akshayk93** [CS370-soft-eng-practicum/geolocationChat#20]
I would likely use this app on my phone rather than a computer, but when I try to send a message using the mobile browser (safari on iPhone), there is no way to send the message. There is no "send" button, and using the enter/return key just goes to the next line rather than submitting the message.

**Comment by arifsundrani** [comment]
Interesting, I was able to use the enter/return key and it worked. I tried it on both Android and iOS. I feel that hitting enter/return is just more intuitive.
