### ISSUE TITLE
Long messages w/o spaces are cut off

### ISSUE THREAD

**Issue by jfbarnes5** [CS370-soft-eng-practicum/geolocationChat#3]
There's no skipping to the next line if the text is too long and with out spaces. For example, there should be a hypen after all the letters that can fit on one line and the remaining letters should be added to the next line. Ya feel me?  TESTTESTESTESTTESTTESTESTESTTESTTESTESTESTTE-
ST instead of TESTTESTESTESTTESTTESTESTESTTESTTESTESTESTTE and the ST are missing from view.

**Comment by arifsundrani** [comment]
fixed by adding word-wrap
