### ISSUE TITLE
I can make two accounts with the same name

### ISSUE THREAD

**Issue by dehjuntzou** [CS370-soft-eng-practicum/geolocationChat#40]
Furthermore, if I use an existing username to create a new username, it says "(form not completed correctly)" on the top. There should be a message saying: "Username Already Exists"

**Comment by ARKilgore** [comment]
This is pretty unclear. In the title you say you **can** do something, and in the description you say you **can't** do that same thing. If your problem is with the error message make a new issue for that. The issue presented in the title does not exist, per your description.
